inherit: 
    - models/standard.yaml
    # - models/small.yaml
    - wandb.yaml

model:
    # n_dims: 2
    n_dims: 6 #cos_sin theta1, cos_sin theta2, theta1_dot, theta2_dot
    n_positions: 1024

training:
    task: linear_regression   # Dont need this, change schema later
    data: gaussian # Dont need this, change schema later
    task_kwargs: {} # Dont need this, change schema later
    epochs: 1 
    batch_size: 4000 
    learning_rate: 0.0003 #0.0001 #train
    save_every_steps: 5000 #1000
    keep_every_steps: 5000 #1000
    train_steps: 6000 #3800
    test_pendulums: 1 #batches of 5000
    test_pendulums_outofdistr: 1 #batches of 5000
    # resume_id: "056764e2-f56a-4e25-8019-3ce5098c388c"
    curriculum:
        dims:
            start: 2
            end: 2
            inc: 1
            interval: 200000000000
        points:
            start: 3500 #560 #400 #2
            end: 3600
            inc: 1
            interval: 2000000000000

wandb:
    name: "acrobot more data shorter with lqr noise, RoPE, and sqrt scaling for control"
    entity: "ebonyesmith-uc-berkeley-electrical-engineering-computer-" #"afrias5"
    project: "test"




# dataset_filesfolder: "./dataset_pendulum" #Folder that stores all your pickle files and logging info
dataset_filesfolder: "/data/esmith/Dataset_Acrobot_AIGymWithNoiseShorter_ICL" #Folder that stores all your pickle files and logging info
pickle_folder: "picklefolder"  # Subfolder of dataset_filesfolder that will have all your trainingpkl files
pickle_folder_test: "picklefolder_test_indistr"  # Subfolder of dataset_filesfolder that will have all your test pkl files
pickle_folder_test_outofdistr: "picklefolder_test_outofdistr"  # Subfolder of dataset_filesfolder that will have all your test pkl files
# dataset_logger_textfile: "dataset_logger.txt" # Used in getData2.py for logging dataset information. Located in dataset_filesfolder
dataset_logger_textfile: "dataset_logger_train.txt" 
dataset_test_logger_textfile: "dataset_test_logger.txt" 
dataset_test_outofdistr_logger_textfile: "dataset_test_outofdistr_logger.txt"


out_dir: ./models/acrobot_cos_sin_theta #Where to store model checkpoints
# out_dir: ./models/cartpole_cos_sin_theta_finetune #Where to store model checkpoints
model_logger_textfile: "testing.txt"   #Name of txt file to save training info. Located it out_dir
test_run: False              # For debugging, this will not save checkpoints or log to wandb
use_chunk: 6000 #3800 #4000 #1 #50                 # How you want to split dataset into chunks. 1 means load everything
loss: "mean_squared_error" #"mean_absolute_error" #"mean_squared_error"   #Specify which loss to use in the tasks.py file
# finetune_from: ./models/cartpole_cos_sin_theta/a1d5f223-6768-4134-934b-4879031f7ea1/checkpoint_epoch1_step274941.pt #Where to load the model from for finetuning
